# Generated by Django 3.0.8 on 2020-07-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authrestapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
